# Generated by Django 5.1.2 on 2024-10-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_store_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='photo_upload',
            field=models.ImageField(blank=True, null=True, upload_to='store_images/'),
        ),
        migrations.AlterField(
            model_name='store',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
