# Generated by Django 5.1.2 on 2024-10-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_photo_upload_alter_store_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='photo_upload',
            field=models.ImageField(blank=True, null=True, upload_to='static/store_images/'),
        ),
    ]
