<<<<<<< HEAD
# Generated by Django 5.1.2 on 2024-10-27 14:01
=======
# Generated by Django 5.1.2 on 2024-10-27 15:43
>>>>>>> e86f565c9e50dec9a1a284b56492edcf0c1f1b8b

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_alter_store_location_alter_store_photo_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='photo_upload',
            field=models.ImageField(blank=True, null=True, upload_to='store_images/'),
        ),
    ]
