<<<<<<< HEAD
# Generated by Django 5.1.2 on 2024-10-27 14:01
=======
>>>>>>> 96142267eefa9f39795c370ba55897f89fbaa7c9

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_alter_store_location_alter_store_photo_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='photo_upload',
            field=models.ImageField(blank=True, null=True, upload_to='store_images/'),
        ),
    ]
