<<<<<<< HEAD
# Generated by Django 5.1.2 on 2024-10-27 13:23
=======
>>>>>>> 372393e155fdc0a1697b8fde36327dccaa5e5e82

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_alter_store_location_alter_store_photo_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='photo_upload',
            field=models.ImageField(blank=True, null=True, upload_to='store_images/'),
        ),
    ]
