# Generated by Django 5.1.2 on 2024-10-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_photo_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
