# Generated by Django 5.1.4 on 2024-12-08 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_photo_url_product_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='photo',
            new_name='photo_url',
        ),
    ]
